title = "Feeds Fun Blog"
subtitle = "News, changelogs and documentation"
author = "Aliaksei Yaletski (Tiendil)"

[[menu]]
  type = "external"
  name = "Feeds Fun"
  url = "https://feeds.fun"

[[menu]]
  type = "feed"
  css_classes = "ti ti-rss"
  name = ""
  tooltip = "News Feed"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-discord"
  name = ""
  tooltip = "Discord server"
  url = "https://discord.gg/C5RVusHQXy"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-reddit"
  name = ""
  tooltip = "Reddit community"
  url = "https://www.reddit.com/r/feedsfun/"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-github"
  name = ""
  tooltip = "GitHub repository"
  url = "https://github.com/Tiendil/feeds.fun"

[license]
url = "http://creativecommons.org/licenses/by-nc-nd/4.0/"
name = "CC BY-NC-ND 4.0"

[tags_translations]
news = "news"
releases = "releases"
documentation = "documentation"
tutorial = "tutorial"
collections = "collections"
gemini = "gemini"
performance = "performance"
feeds-discovery = "feeds discovery"
rules = "rules"
gui = "gui"
docker = "docker"
monthly-recap = "monthly recap"

[theme_translations]
tags_filter_header = 'Texts:'
last_posts_header = 'Last texts'
article_similar_header = 'Read next'
